#set( $symbol_dollar = '$' )
@startuml

[${rootArtifactId}-start（启动入口）] --> [${rootArtifactId}-adapter（适配层）]
[${rootArtifactId}-adapter（适配层）] --> [${rootArtifactId}-app（应用层）]: 入站适配，数据组装
[${rootArtifactId}-app（应用层）] --> [${rootArtifactId}-client（API层）]: 实现接口
[${rootArtifactId}-app（应用层）] --> [${rootArtifactId}-domain（领域层）]: CQRS 增删改命令
[${rootArtifactId}-app（应用层）] --> [${rootArtifactId}-infrastructure（基础设施层）]: CQRS 查询视图
[${rootArtifactId}-infrastructure（基础设施层）] --> [${rootArtifactId}-domain（领域层）]: 依赖倒置

cloud APP
cloud 其他应用服务
cloud 第三方接口
cloud 分布式调度平台

database MySQL
database Redis
database MQ
database Elasticsearch
database MongoDB

http - [${rootArtifactId}-adapter（适配层）]: REST 接口
[APP] ..> http: 前后端对接

[${rootArtifactId}-adapter（适配层）] - rpc: Dubbo 接口
[其他应用服务] ..> rpc: 网络调用
[其他应用服务] ..> [${rootArtifactId}-client（API层）]: 代码集成

[${rootArtifactId}-adapter（适配层）] ..> MQ: 消费消息
[分布式调度平台] ..> [${rootArtifactId}-adapter（适配层）]: 触发任务

[${rootArtifactId}-infrastructure（基础设施层）] ..> MySQL: 读写数据
[${rootArtifactId}-infrastructure（基础设施层）] ..> Elasticsearch: 读写索引
[${rootArtifactId}-infrastructure（基础设施层）] ..> MongoDB: 读写数据
[${rootArtifactId}-infrastructure（基础设施层）] ..> MQ: 生产消息
[${rootArtifactId}-infrastructure（基础设施层）] ..> Redis: 读写缓存
[${rootArtifactId}-infrastructure（基础设施层）] ..> 第三方接口: 接口调用

@enduml
