#set( $symbol_dollar = '$' )
@startuml
[${rootArtifactId}-start（启动入口）] --> [${rootArtifactId}-web（请求控制层）]
[${rootArtifactId}-web（请求控制层）] --> [${rootArtifactId}-service（业务逻辑服务层）]
[${rootArtifactId}-service（业务逻辑服务层）] --> [${rootArtifactId}-model（数据模型层）]

database MySQL

[APP] --> http: 前端请求
http - [${rootArtifactId}-web（请求控制层）]: 暴露 REST 接口
[${rootArtifactId}-model（数据模型层）] ..> MySQL : 数据持久化

@enduml
