#set( $symbol_dollar = '$' )
@startuml "时序图"

autonumber

"外部请求（WEB）" -> "${rootArtifactId}-web": 发送请求报文
"${rootArtifactId}-web" -> "${rootArtifactId}-service": 调用业务逻辑层
"${rootArtifactId}-service" -> "${rootArtifactId}-model": 调用数据访问层
"${rootArtifactId}-model" -> "存储组件（DB）": 执行数据库读写操作
"${rootArtifactId}-model" --> "${rootArtifactId}-service": 返回数据库执行结果
"${rootArtifactId}-service" --> "${rootArtifactId}-web": 组装数据响应报文

@enduml
